// t145-packaging-parity: the package determinism and clean-build guard.
//
// covers: file:scripts/package.ts, file:harness/claude/manifest.ts, file:harness/codex/emit.ts
//
// WHAT. The one-core-N-harnesses layout (dist-unified MR-1) makes dist/ a
// GENERATED artifact: `bun scripts/package.ts` projects the harness-neutral
// core/ tree + harness/<name>/ surfaces into ignored local dist/ and
// dist-release/ roots. `package.ts --check` builds all selected projections
// twice in independent temp roots and byte-compares those builds.
//
// This test IS that guard, run from the suite: it asserts `package.ts --check`
// exits 0 from source alone and rejects an intentionally nondeterministic
// emitter. Existing local generated bytes are never inputs to the check.
//
// WHY A SUBPROCESS. package.ts is a CLI that spawns the in-tree generators
// (aidlc-graph compile, aidlc-runner-gen) per harness; running it as a child
// mirrors how a developer or CI invokes it, and isolates its temp-dir builds
// from the suite's process.

import { describe, expect, test } from "bun:test";
import { spawnSync } from "node:child_process";
import {
  cpSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  readdirSync,
  rmSync,
  symlinkSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const PACKAGE_TS = join(REPO_ROOT, "scripts", "package.ts");
const CHECK_TIMEOUT_MS = 180_000;

type Run = ReturnType<typeof spawnSync>;

interface HookEntry {
  command: string;
}

interface HookGroup {
  hooks: HookEntry[];
}

interface HooksConfig {
  hooks: Record<string, HookGroup[]>;
}

function copyDir(src: string, dst: string): void {
  cpSync(src, dst, { recursive: true });
}

function makeFixture(harness: string, sourceHarness = harness): string {
  const root = mkdtempSync(join(tmpdir(), "aidlc-package-contract-"));
  copyDir(join(REPO_ROOT, "core"), join(root, "core"));
  copyDir(join(REPO_ROOT, "scripts"), join(root, "scripts"));
  cpSync(join(REPO_ROOT, "package.json"), join(root, "package.json"));
  cpSync(join(REPO_ROOT, "bun.lock"), join(root, "bun.lock"));
  mkdirSync(join(root, "harness"), { recursive: true });
  copyDir(join(REPO_ROOT, "harness", sourceHarness), join(root, "harness", harness));
  // Emitter imports (notably smol-toml) resolve from the checkout, not from
  // Bun's mutable global package cache.
  const nodeModules = join(REPO_ROOT, "node_modules");
  if (existsSync(nodeModules)) {
    symlinkSync(
      nodeModules,
      join(root, "node_modules"),
      process.platform === "win32" ? "junction" : "dir",
    );
  } else if (sourceHarness === "codex") {
    const cache = spawnSync(process.execPath, ["pm", "cache"], {
      encoding: "utf-8",
    });
    const cacheRoot = (cache.stdout ?? "").trim();
    const packageJson = JSON.parse(
      readFileSync(join(REPO_ROOT, "package.json"), "utf-8"),
    ) as { devDependencies?: Record<string, string> };
    const version = packageJson.devDependencies?.["smol-toml"];
    const cached =
      cache.status === 0 && version
        ? readdirSync(cacheRoot).find((name) =>
            name.startsWith(`smol-toml@${version}`),
          )
        : undefined;
    if (!cached) throw new Error("smol-toml is unavailable in Bun's package cache");
    copyDir(
      join(cacheRoot, cached),
      join(root, "node_modules", "smol-toml"),
    );
  }
  return root;
}

function runPackage(root: string, ...args: string[]): Run {
  return spawnSync("bun", [join(root, "scripts", "package.ts"), ...args], {
    cwd: root,
    encoding: "utf-8",
    timeout: CHECK_TIMEOUT_MS - 5_000,
  });
}

function output(run: Run): string {
  return `${run.stdout ?? ""}${run.stderr ?? ""}`;
}

function replaceOnce(file: string, from: string, to: string): void {
  const before = readFileSync(file, "utf-8");
  expect(before.split(from)).toHaveLength(2);
  writeFileSync(file, before.replace(from, to));
}

describe("t145 package determinism — two source-only builds match", () => {
  test("scripts/package.ts exists (the build entry)", () => {
    expect(existsSync(PACKAGE_TS)).toBe(true);
  });

  test("package.ts --check exits 0 for two independent complete builds", () => {
    const res = spawnSync("bun", [PACKAGE_TS, "--check"], {
      cwd: REPO_ROOT,
      encoding: "utf-8",
      timeout: CHECK_TIMEOUT_MS - 5_000,
    });
    if (res.status !== 0) {
      console.error(`package --check output:\n${res.stdout ?? ""}${res.stderr ?? ""}`);
    }
    expect(res.status).toBe(0);
  }, CHECK_TIMEOUT_MS);

  test("package.ts claude --check is clean without reading local projections", () => {
    const res = spawnSync("bun", [PACKAGE_TS, "claude", "--check"], {
      cwd: REPO_ROOT,
      encoding: "utf-8",
      timeout: CHECK_TIMEOUT_MS - 5_000,
    });
    if (res.status !== 0) {
      console.error(`package claude --check output:\n${res.stdout ?? ""}${res.stderr ?? ""}`);
    }
    expect(res.status).toBe(0);
    expect(res.stdout).toContain(
      "package --check: deterministic across two independent build(s) for claude.",
    );
  }, CHECK_TIMEOUT_MS);

  test("generated distribution roots are ignored developer outputs", () => {
    const ignored = spawnSync(
      "git",
      ["check-ignore", "dist/claude/.claude", "dist-release/claude/.claude"],
      { cwd: REPO_ROOT, encoding: "utf-8" },
    );
    expect(ignored.status).toBe(0);
    expect(ignored.stdout).toContain("dist/claude/.claude");
    expect(ignored.stdout).toContain("dist-release/claude/.claude");
  });
});

describe("t145 packager contract regressions", () => {
  test("a synthetic harness uses the default orchestrator path and passes harnessDir to tools", () => {
    const root = makeFixture("foo", "claude");
    try {
      const manifest = join(root, "harness", "foo", "manifest.ts");
      replaceOnce(manifest, 'name: "claude"', 'name: "foo"');
      replaceOnce(manifest, 'harnessDir: ".claude"', 'harnessDir: ".foo"');
      replaceOnce(
        manifest,
        'orchestratorSkillPath: ".claude/skills/aidlc/SKILL.md",',
        "",
      );

      const run = runPackage(root, "foo");
      expect(output(run)).toContain("[foo] regenerated dist/foo/.foo");
      expect(run.status).toBe(0);

      const generated = join(root, "dist", "foo", ".foo");
      const descriptor = JSON.parse(
        readFileSync(join(generated, "tools", "data", "harness.json"), "utf-8"),
      );
      const graph = readFileSync(
        join(generated, "tools", "data", "stage-graph.json"),
        "utf-8",
      );
      const runner = readFileSync(
        join(generated, "skills", "aidlc-init", "SKILL.md"),
        "utf-8",
      );
      expect(descriptor.name).toBe("foo");
      expect(descriptor.harnessDir).toBe(".foo");
      expect(graph).toContain('"path": ".foo/sensors/');
      expect(graph).not.toContain('"path": ".claude/sensors/');
      expect(runner).toContain("bun .foo/tools/aidlc.ts engine intent create");
      expect(runner).not.toContain("bun .claude/tools/aidlc.ts");
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  }, CHECK_TIMEOUT_MS);

  test("a codex emitter honors a renamed manifest harnessDir", () => {
    const root = makeFixture("foo", "codex");
    try {
      const manifest = join(root, "harness", "foo", "manifest.ts");
      replaceOnce(manifest, 'name: "codex"', 'name: "foo"');
      replaceOnce(manifest, 'harnessDir: ".codex"', 'harnessDir: ".foo"');

      const run = runPackage(root, "foo");
      expect(output(run)).toContain("[foo] regenerated dist/foo/.foo");
      expect(run.status).toBe(0);

      const distRoot = join(root, "dist", "foo");
      const generated = join(distRoot, ".foo");
      expect(existsSync(generated)).toBe(true);
      expect(existsSync(join(distRoot, ".codex"))).toBe(false);

      const hooks = JSON.parse(
        readFileSync(join(generated, "hooks.json"), "utf-8"),
      ) as HooksConfig;
      const commands = Object.values(hooks.hooks)
        .flat()
        .flatMap((group) => group.hooks.map((hook) => hook.command));
      expect(commands.length).toBeGreaterThan(0);
      expect(
        commands.every((command: string) =>
          command.startsWith("bun .foo/tools/aidlc.ts engine adapter foo")
        ),
      ).toBe(true);

      const rules = readFileSync(join(generated, "rules", "default.rules"), "utf-8");
      expect(rules).toContain('pattern = ["bun", ".foo/tools/"]');
      expect(rules).not.toContain('pattern = ["aidlc"]');
      expect(rules).not.toContain('["bun", ".codex/');

      const trustSeed = readFileSync(join(generated, "trust-seed.toml"), "utf-8");
      expect(trustSeed).toContain("<PROJECT_DIR>/.foo/hooks.json:");
      expect(trustSeed).not.toContain("<PROJECT_DIR>/.codex/hooks.json:");

      const runner = readFileSync(
        join(distRoot, ".agents", "skills", "aidlc-init", "SKILL.md"),
        "utf-8",
      );
      expect(runner).toContain("bun .foo/tools/aidlc.ts engine intent create");
      expect(runner).not.toContain("bun .codex/tools/aidlc.ts");
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  }, CHECK_TIMEOUT_MS);

  test("write mode derives the graph when a harnessDir is renamed", () => {
    const root = makeFixture("claude");
    try {
      const manifest = join(root, "harness", "claude", "manifest.ts");
      replaceOnce(manifest, 'harnessDir: ".claude"', 'harnessDir: ".foo"');
      replaceOnce(
        manifest,
        'orchestratorSkillPath: ".claude/skills/aidlc/SKILL.md"',
        'orchestratorSkillPath: ".foo/skills/aidlc/SKILL.md"',
      );

      const run = runPackage(root, "claude");
      expect(output(run)).toContain("[claude] regenerated dist/claude/.foo");
      expect(run.status).toBe(0);
      expect(existsSync(join(root, "dist", "claude", ".claude"))).toBe(false);

      const generated = join(root, "dist", "claude", ".foo");
      expect(
        readFileSync(join(generated, "tools", "data", "stage-graph.json"), "utf-8"),
      ).toContain('"path": ".foo/sensors/');
      expect(
        readFileSync(join(generated, "skills", "aidlc-init", "SKILL.md"), "utf-8"),
      ).toContain("bun .foo/tools/aidlc.ts engine intent create");
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  }, CHECK_TIMEOUT_MS);

  test("an explicitly named harness without a manifest exits nonzero", () => {
    const root = makeFixture("kiro");
    try {
      const run = runPackage(root, "does-not-exist");
      expect(run.status).not.toBe(0);
      expect(output(run)).toContain('unknown harness "does-not-exist"');
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  }, CHECK_TIMEOUT_MS);

  test("--check works from a fixture with no generated roots and remains temp-only", () => {
    const root = makeFixture("claude");
    try {
      const run = runPackage(root, "claude", "--check");
      expect(run.status, output(run)).toBe(0);
      expect(existsSync(join(root, "dist"))).toBe(false);
      expect(existsSync(join(root, "dist-release"))).toBe(false);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  }, CHECK_TIMEOUT_MS);

  test("--check ignores corrupted local generated bytes", () => {
    const root = makeFixture("claude");
    try {
      const copyJunk = join(root, "dist", "claude", "local-only.txt");
      const releaseJunk = join(root, "dist-release", "claude", "local-only.txt");
      mkdirSync(dirname(copyJunk), { recursive: true });
      mkdirSync(dirname(releaseJunk), { recursive: true });
      writeFileSync(copyJunk, "corrupt copy output\n");
      writeFileSync(releaseJunk, "corrupt release output\n");
      const run = runPackage(root, "claude", "--check");
      expect(run.status, output(run)).toBe(0);
      expect(readFileSync(copyJunk, "utf-8")).toBe("corrupt copy output\n");
      expect(readFileSync(releaseJunk, "utf-8")).toBe("corrupt release output\n");
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  }, CHECK_TIMEOUT_MS);

  test("--check reports the path emitted nondeterministically", () => {
    const root = makeFixture("claude");
    try {
      const manifest = join(root, "harness", "claude", "manifest.ts");
      replaceOnce(
        manifest,
        "  emit: null,",
        `  emit: ({ distRoot }) => {
    const fs = require("node:fs");
    const path = require("node:path");
    fs.writeFileSync(
      path.join(distRoot, ".claude", "tools", "data", "nondeterministic.txt"),
      \`\${Math.random()}\\n\`,
    );
  },`,
      );
      const run = runPackage(root, "claude", "--check");
      expect(run.status).not.toBe(0);
      expect(output(run).replaceAll("\\", "/")).toContain(
        "DIFFERS between builds: dist/claude/.claude/tools/data/nondeterministic.txt",
      );
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  }, CHECK_TIMEOUT_MS);

  test("full write removes generated harness and plugin roots absent from source", () => {
    const root = makeFixture("claude");
    try {
      const staleHarness = join(root, "dist", "removed-harness", "stale.txt");
      const staleReleaseHarness = join(
        root,
        "dist-release",
        "removed-harness",
        "stale.txt",
      );
      const stalePlugin = join(
        root,
        "dist",
        "plugins",
        "removed-plugin",
        "claude",
        "stale.txt",
      );
      for (const path of [staleHarness, staleReleaseHarness, stalePlugin]) {
        mkdirSync(dirname(path), { recursive: true });
        writeFileSync(path, "stale\n");
      }

      const run = runPackage(root);
      expect(run.status, output(run)).toBe(0);
      expect(existsSync(join(root, "dist", "removed-harness"))).toBe(false);
      expect(existsSync(join(root, "dist-release", "removed-harness"))).toBe(false);
      expect(existsSync(join(root, "dist", "plugins", "removed-plugin"))).toBe(false);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  }, CHECK_TIMEOUT_MS);

  test("write mode replaces only the named generated root", () => {
    const root = makeFixture("kiro");
    try {
      const stale = join(root, "dist", "kiro", "removed-root-output.txt");
      const pluginAsset = join(root, "dist", "plugins", "fixture", "keep.txt");
      const unrelatedAsset = join(root, "dist", "unrelated-root-asset.txt");
      mkdirSync(dirname(stale), { recursive: true });
      writeFileSync(stale, "stale\n");
      mkdirSync(dirname(pluginAsset), { recursive: true });
      writeFileSync(pluginAsset, "keep plugin\n");
      writeFileSync(unrelatedAsset, "keep root\n");

      const run = runPackage(root, "kiro");
      expect(run.status).toBe(0);
      expect(existsSync(stale)).toBe(false);
      expect(readFileSync(pluginAsset, "utf-8")).toBe("keep plugin\n");
      expect(readFileSync(unrelatedAsset, "utf-8")).toBe("keep root\n");
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  }, CHECK_TIMEOUT_MS);
});
